Home page update
StevensSEC/softe.club pull request #287
Opened 2021-09-08 19:00 UTC by carpenterd777

- Add recordings page
- Move contributions to own page
- add styling to contributions view
- allow article list to grow freely

These changes aim to clean up the home page. Old material that is no longer relevant to the current semester long project is moved from the home page
to other locations in the website, such as pages accessibile in the "more" sidebar. The scrolling feature of the article list was removed to enhance the
feel of navigation but not having to deal with nested scroll bars.

2021-09-08 20:01 UTC, dyc3 commented
FYI, the time in the flyer and the time shown on the website for GBM 1 is different

2021-09-08 20:09 UTC, dyc3 requested changes
Recordings and Contributions pages don't have great alignment

![image](https://user-images.githubusercontent.com/1808807/132577903-7853695e-900a-417a-a1e4-a9d33b58c03e.png)

![image](https://user-images.githubusercontent.com/1808807/132578022-c2fe53cc-569b-4199-b41e-cf46a194a802.png)

2021-09-08 20:09 UTC, dyc3 commented on src/views/Contributions/Contributions.js
> +				<SEC.Link href="https://github.com/orgs/StevensSEC/projects/3">
this is not updated

2021-09-08 20:38 UTC, carpenterd777 commented
> 
> 
> FYI, the time in the flyer and the time shown on the website for GBM 1 is different

yeahhhhh I'm trying to get that fixed now in #286

2021-09-10 14:46 UTC, dyc3 approved these changes

2021-09-10 14:46 UTC, merged