SLP Redesign
StevensSEC/softe.club pull request #295
Opened 2021-09-11 05:54 UTC by carpenterd777

This aims to overhaul the SLP page to a design that is less cluttered. Contributions have been moved to the contributions page created prior. The SLP page instead focuses more on describing each project and showing a sequential history of each SLP. Several components and view have been ported to typescript; this PR will require 291 to be merged in first.

Fixes #110

- install typescript
- add config file
- install webpack plugins
- add create-react-app tsconfig to extend
- port event banner to typescript
- Create local variable rather than extend props
- Ran linter
- Enable strict null checks
- Update file extension in test
- Update type of prop
- Mark optional props as optional
- Use the null coalescing operator
- add react-router-dom types
- create SLP component
- overhaul SLP page using new component
- add a heading
- extract fetch article function to own module
- article uses extracted fetch article
- slp component now fetches markdown
- rename to fetch markdown
- add contributions to contributions page
- convert contributions to typescript
- converted projects file to typescript
- add some responsiveness
- add pokemonbatlelib
- fix accent characters
- add monocle project
- make contributions style consistent with rest of page
- converted contributions component to typescript
- Ran the linter

2021-09-11 06:00 UTC, carpenterd777 commented
I see that the tests are failing. What is webpack trying to tell me?

2021-09-11 14:11 UTC, dyc3 commented
Maybe there's cyclic reference and it can't separate the code into chunks? Haven't looked at the code yet

2021-09-12 15:08 UTC, dyc3 requested changes

2021-09-12 15:08 UTC, dyc3 commented on src/modules/fetchMarkdown.ts
> +const fnFetchMarkdown = (
We're duplicating functionality here. Can we rework this so we can just have one function, and make it a little more simple to use?

2021-09-22 22:19 UTC, carpenterd777 commented
refactored, but a test will fail. for some reason `fetch` is being called twice?

2021-09-22 23:52 UTC, dyc3 requested changes

2021-09-22 23:52 UTC, dyc3 commented on src/utils/fetchMarkdown.ts
> +interface MarkdownResult {
nit, would prefer this instead of `export type ...` at the bottom
```suggestion
export interface MarkdownResult {
```

2021-09-22 23:52 UTC, dyc3 commented on src/utils/fetchMarkdown.ts
> +		__previousSource: source,
`__previousSource` doesn't really make any sense in this context. Is there anything preventing us from moving this out?

2021-09-22 23:52 UTC, dyc3 commented on src/views/Contributions/Contributions.tsx
> +	const [__previousSource, setPreviousSource] = useState("");
nit, I'd prefer a single state object since they both change at the same time.

2021-09-23 00:25 UTC, carpenterd777 commented
sorry I also converted the ArticleView component into typescript as a bonus, lack of intellisense there was killing me

2021-09-23 14:39 UTC, dyc3 approved these changes

2021-09-23 14:39 UTC, merged