fix: use a square sized image
StevensSEC/softe.club pull request #322
Opened 2022-11-12 22:51 UTC by MHKhan18

2022-11-12 22:52 UTC, MHKhan18 commented
the image breaks up on zooming

2022-11-12 22:56 UTC, dyc3 requested changes
This image is 2560px, which is 9 MB. The original image is not even close to that size, so there is a lot of wasted data here. This will severely hurt load times, and will count significantly towards firebase's monthly 10gb bandwidth limit.

2022-11-12 22:59 UTC, MHKhan18 commented
> This image is 2560px, which is 9 MB. The original image is not even close to that size, so there is a lot of wasted data here. This will severely hurt load times, and will count significantly towards firebase's monthly 10gb bandwidth limit.

It must have been adobe doing something funny. I'll try reducing the image size.

2022-11-13 01:31 UTC, dyc3 approved these changes

2022-11-13 01:32 UTC, merged